### ISSUE TITLE
项目打包之后出现问题

### ISSUE THREAD

**Issue by mynameisasa** [jiangteng2019/satellite-track#1]
项目build之后，用nginx部署项目的时候，请求cesium里面的一些信息的时候，出现下面的错误：
VM336:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

cesiumWorkerBootstrapper.js:1 Uncaught SyntaxError: Unexpected token '<' (at cesiumWorkerBootstrapper.js:1:1)

这是我打包的问题吗

**Comment by jiangteng2019** [comment]
有可能，建议使用高版本的nodejs打包试一下。

**Comment by mynameisasa** [comment]
能告知一下您那边使用的版本吗，我现在本地用的是V18.17.0这个版本的。

**Comment by jiangteng2019** [comment]
我本地使用的是 v16.14.0。如果你的开发环境是正常的，看报错应该是打包之后的路径问题。可以检查一下资源引用的路径。

**Comment by mynameisasa** [comment]
昨晚上又试了T.T，把router/index.js里面的history 模式改了createWebHistory 和createWebHashHistory ，都还是有出现这个问题，或者还需要注意修改其他地方的文件吗
nginx里面的配置是这样的
		listen       5173;
		server_name  10.71.2.100;
		location / {
			 root   html;
			 index  index.html index.htm;
			 try_files $uri $uri/ /index.html; # 防止页面刷新404
			 autoindex  on;
		}

**Comment by jiangteng2019** [comment]
这是线上部署的nginx配置。但你的看起来没什么问题。
![image](https://github.com/jiangteng2019/satellite-track/assets/25784016/f02d18ec-6fb2-4628-97f8-88c04f0852fb)

**Comment by jiangteng2019** [comment]
如果你的项目没有放在nginx的根目录下，需要在项目中配置公共基础路径，并且要与线上环境保持统一。
